PATH_CODE = "Code/"
require (PATH_CODE..'_defines')
STIGMA_LIB = require (PATH_LIB..'lua-stigma-lib/StigmaLib')
TLfres = require(PATH_CODE..'TLfres')
require (PATH_CODE..'_debug')
require (PATH_CODE..'_globals')
GAMESYS = require (PATH_CODE_GAMESYSTEM..'_gameSystem')
require (PATH_CODE_GAMESYSTEM..'_tetrominos')
GRID = require (PATH_CODE_GAMESYSTEM..'_grid')
require (PATH_CODE..'_soundsystem')
require (PATH_CODE..'_graphicsystem')
require (PATH_CODE..'_animsystem')
require (PATH_CODE_GAMESYSTEM..'animations')
